title: Xuetong Yuan
logo: /assets/img/avatar.jpg
description: PhD student in linguistics at University of Connecticut
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

github:
  cv_url: https://drive.google.com/open?id=11vbPUYCgCBjsuuFDrVfmgQtHG63iVLvS
  slides_url: https://drive.google.com/open?id=1FVLrZuB1UWb8gKZsTLl51EWy0KZ9eT0W
  paper_url: https://drive.google.com/open?id=12AaoNRO0YGCrUDs9sZZL8-J7HzxQ6R5k

collections:
  p:
    output:         true
    permalink:      /:collection/:path
