title: Xuetong Yuan
logo: /assets/img/avatar.jpg
description: A VeRy GuD LINGUIST
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

github:
  cv_url: https://drive.google.com/file/d/1Z80S9Rq3j82kO6izhOW6Icm_-izFSfCw/view?usp=sharing

collections:
  p:
    output:         true
    permalink:      /:collection/:path
